[workspace]
resolver = "2"
members = ["day01", "day02", "day03", "day04", "day05", "util"]

[workspace.dependencies]
anyhow = "1.0.93"
nom = "7.1.3"
util = { path = "./util" }

[profile.release]
lto = true
panic = "abort"
strip = "symbols"
